import { LogOut, Package, Save, Settings, Users } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api } from '../services/api'
import { useStore } from '../store/StoreContext'
import type { QuoteStatus } from '../types'

export function AdminPage({ navigate }: { navigate: (path: string) => void }) {
  const store = useStore(); const [session, setSession] = useState(api.getAdminSession()); const [tab, setTab] = useState<'quotes'|'products'|'settings'>('quotes'); const [error, setError] = useState('')
  const login = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { const next = await api.loginAdmin(String(data.get('username')), String(data.get('password'))); setSession(next); location.reload() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Đăng nhập thất bại') } }
  if (!session) return <main className="admin-login"><form onSubmit={login}><img src={store.settings.logoWideSrc} alt="DTPT Techs" /><h1>Quản trị hệ thống</h1><label>Tên đăng nhập<input name="username" required /></label><label>Mật khẩu<input name="password" type="password" required /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button">Đăng nhập</button><button type="button" className="text-button" onClick={() => navigate('/')}>Về trang chủ</button></form></main>
  const statuses: QuoteStatus[] = ['new','reviewing','quoted','won','closed']
  return <main className="admin"><aside><img src={store.settings.logoWideSrc} alt="DTPT Techs" /><button className={tab === 'quotes' ? 'active' : ''} onClick={() => setTab('quotes')}><Users /> Yêu cầu báo giá</button><button className={tab === 'products' ? 'active' : ''} onClick={() => setTab('products')}><Package /> Sản phẩm</button><button className={tab === 'settings' ? 'active' : ''} onClick={() => setTab('settings')}><Settings /> Cấu hình</button><button onClick={() => { api.logoutAdmin(); setSession(null) }}><LogOut /> Đăng xuất</button></aside><section><div className="admin-title"><div><span className="eyebrow">DTPT CONTROL CENTER</span><h1>{tab === 'quotes' ? 'Yêu cầu báo giá' : tab === 'products' ? 'Danh mục sản phẩm' : 'Cấu hình website'}</h1></div><button className="secondary-button" onClick={() => navigate('/')}>Xem website</button></div>{tab === 'quotes' && <div className="admin-table">{store.quotes.length === 0 ? <div className="empty-results"><h2>Chưa có yêu cầu mới</h2></div> : store.quotes.map(quote => <article key={quote.id}><div><strong>{quote.customer.company}</strong><span>{quote.customer.name} · {quote.customer.phone}</span><small>{quote.id} · {new Date(quote.createdAt).toLocaleString('vi-VN')}</small></div><div><b>{quote.items.length} sản phẩm</b><p>{quote.customer.note}</p></div><select value={quote.status} onChange={event => store.updateQuoteStatus(quote.id, event.target.value as QuoteStatus)}>{statuses.map(status => <option key={status}>{status}</option>)}</select></article>)}</div>}{tab === 'products' && <div className="admin-table">{store.products.map(product => <article key={product.id}><div><strong>{product.name}</strong><span>{product.brand} · {product.model}</span></div><div><b>{product.category}</b><p>{product.price?.toLocaleString('vi-VN')} ₫</p></div><span className="status-pill">{product.status}</span></article>)}</div>}{tab === 'settings' && <SettingsForm />}</section></main>
}
function SettingsForm() { const { settings, updateSettings } = useStore(); const [form, setForm] = useState(settings); const submit = async (event: FormEvent) => { event.preventDefault(); await updateSettings(form); alert('Đã lưu cấu hình') }; return <form className="settings-form" onSubmit={submit}><label>Tên thương hiệu<input value={form.storeName} onChange={event => setForm({ ...form, storeName: event.target.value })} /></label><label>Slogan<input value={form.slogan} onChange={event => setForm({ ...form, slogan: event.target.value })} /></label><label>Điện thoại<input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></label><label>Email<input value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label className="full">Địa chỉ<input value={form.address} onChange={event => setForm({ ...form, address: event.target.value })} /></label><button className="primary-button full"><Save /> Lưu cấu hình</button></form> }
