import { Mail, MapPin, Phone } from 'lucide-react'
import { useStore } from '../store/StoreContext'

export function BuyingGuidePage({ onQuote }: { onQuote: () => void }) {
  const { settings } = useStore()
  return <main>
    <section className="page-hero"><div className="container"><span className="eyebrow">THÔNG TIN DOANH NGHIỆP & HƯỚNG DẪN MUA HÀNG</span><h1>Rõ thông tin. Đúng thiết bị.</h1><p>Tìm hiểu đơn vị cung cấp, cách yêu cầu báo giá và những thông tin cần xác nhận trước khi đặt hàng.</p></div></section>
    <section className="section"><div className="container buying-guide">
      <article className="business-card"><span className="eyebrow">ĐƠN VỊ VẬN HÀNH WEBSITE</span><h2>CÔNG TY TNHH DTPT-TECHS</h2><p>Giấy CNĐKDN: <strong>0110774870</strong> · Ngày cấp: 05/07/2024</p><p>Cơ quan cấp: Phòng Đăng ký kinh doanh – Sở Kế hoạch và Đầu tư Hà Nội.</p><p><MapPin /> Địa chỉ ĐKKD: {settings.address}</p><p>Vui lòng liên hệ trước nếu cần gặp trực tiếp hoặc xem thiết bị; địa chỉ đăng ký không đồng nghĩa với kho hàng hay showroom.</p><div className="contact-actions"><a className="primary-button" href={`tel:${settings.phone.replace(/\D/g, '')}`}><Phone />{settings.phone}</a><a className="secondary-button" href={`mailto:${settings.email}`}><Mail />{settings.email}</a></div></article>
      <article id="dat-hang"><h2>Từ nhu cầu đến đặt hàng</h2><ol className="buying-steps"><li><strong>Gửi nhu cầu</strong><p>Chọn thiết bị hoặc mô tả ứng dụng, giao thức, số lượng, ngân sách và thời điểm cần hàng. Có thể gửi qua biểu mẫu, Zalo hoặc email.</p></li><li><strong>Xác nhận phương án và báo giá</strong><p>Đối chiếu model, phiên bản, phụ kiện, tình trạng hàng, VAT, chi phí vận chuyển và thời gian giao dự kiến. Giá công khai áp dụng theo ghi chú của từng sản phẩm.</p></li><li><strong>Thống nhất điều kiện đặt hàng</strong><p>Chỉ xác nhận đơn sau khi thống nhất bằng văn bản về giá, thanh toán, giao nhận, bảo hành và điều kiện đổi trả. Yêu cầu báo giá không tự tạo nghĩa vụ thanh toán.</p></li><li><strong>Nhận hàng và đối chiếu</strong><p>Kiểm tra model, số lượng, phụ kiện và chứng từ theo thỏa thuận. Liên hệ DTPT Techs nếu có sai lệch hoặc cần hỗ trợ kỹ thuật.</p></li></ol></article>
      <article id="bao-hanh"><h2>Bảo hành, giao hàng và đổi trả</h2><p>Thời gian trên trang sản phẩm là thông tin để trao đổi ban đầu. Phạm vi bảo hành, nơi tiếp nhận, chi phí vận chuyển và điều kiện đổi trả cần được xác nhận theo đúng model và đơn hàng trong báo giá hoặc hợp đồng.</p><p>Với hàng đặt theo cấu hình, vui lòng xác nhận khả năng thay đổi hoặc hủy đơn trước khi thanh toán. Chưa có chính sách đổi trả chung được công bố trên website.</p></article>
      <article id="bao-mat"><h2>Thông tin liên hệ bạn cung cấp</h2><p>Biểu mẫu thu thập họ tên, số điện thoại, cùng email, đơn vị và nội dung nhu cầu nếu bạn cung cấp. Yêu cầu gửi trực tuyến được lưu để đội ngũ phụ trách xử lý báo giá và liên hệ lại.</p><p>Danh sách thiết bị được lưu trong trình duyệt để bạn tiếp tục lựa chọn. Khi bật dịch vụ thống kê, website ghi nhận lượt xem, trang truy cập, nguồn giới thiệu và loại thiết bị để đánh giá hiệu quả nội dung.</p><p>Bạn có thể liên hệ <a href={`mailto:${settings.email}`}>{settings.email}</a> để yêu cầu kiểm tra, chỉnh sửa hoặc xóa thông tin đã gửi. Không gửi mật khẩu, thông tin thẻ hoặc tài liệu nhạy cảm trong biểu mẫu.</p></article>
      <article><h2>Chưa xác định được model?</h2><p>Gửi bài toán thực tế. Với hệ thống đang vận hành, ảnh nhãn máy, sơ đồ kết nối và thông số nguồn giúp việc trao đổi chính xác hơn.</p><button className="primary-button" onClick={onQuote}>Gửi nhu cầu tư vấn</button></article>
    </div></section>
  </main>
}
