import { SlidersHorizontal } from 'lucide-react'
import { useMemo, useState } from 'react'
import { ProductCard } from '../components/ProductCard'
import { useStore } from '../store/StoreContext'

export function CatalogPage({ params, navigate }: { params: URLSearchParams; navigate: (path: string) => void }) {
  const { products, addToQuote, settings } = useStore(); const [sort, setSort] = useState('featured'); const category = params.get('category') || ''; const query = (params.get('q') || '').toLowerCase()
  const categories = settings.categories.filter(item => item.visible).sort((a, b) => a.sortOrder - b.sortOrder)
  const filtered = useMemo(() => products.filter(product => product.status === 'active' && (!category || product.category === category) && (!query || `${product.name} ${product.model} ${product.brand} ${product.category} ${(product.tags || []).join(' ')}`.toLowerCase().includes(query))).sort((a,b) => sort === 'price-asc' ? (a.price || Infinity) - (b.price || Infinity) : sort === 'price-desc' ? (b.price || 0) - (a.price || 0) : sort === 'order' ? (a.sortOrder || 9999) - (b.sortOrder || 9999) : Number(b.featured) - Number(a.featured)), [products, category, query, sort])
  const changeCategory = (value: string) => navigate(`/san-pham${value ? `?category=${encodeURIComponent(value)}` : ''}`)
  return <main><section className="page-hero"><div className="container"><span className="eyebrow">CATALOGUE DTPT TECHS</span><h1>{category || 'Thiết bị công nghiệp'}</h1><p>{category ? categories.find(item => item.name === category)?.description : 'Khám phá danh mục công nghệ cho nhà máy, hệ thống tự động hóa và phòng nghiên cứu.'}</p></div></section><section className="section"><div className="container catalog-layout"><aside className="filters"><h3><SlidersHorizontal /> Ngành hàng</h3><button className={!category ? 'active' : ''} onClick={() => changeCategory('')}>Tất cả <span>{products.filter(item => item.status === 'active').length}</span></button>{categories.map(item => <button key={item.id} className={category === item.name ? 'active' : ''} onClick={() => changeCategory(item.name)}>{item.name}<span>{products.filter(product => product.status === 'active' && product.category === item.name).length}</span></button>)}</aside><div className="catalog-main"><div className="catalog-toolbar"><p><strong>{filtered.length}</strong> sản phẩm phù hợp</p><select value={sort} onChange={event => setSort(event.target.value)}><option value="featured">Nổi bật</option><option value="order">Thứ tự tùy chỉnh</option><option value="price-asc">Giá thấp đến cao</option><option value="price-desc">Giá cao đến thấp</option></select></div>{filtered.length ? <div className="product-grid">{filtered.map(product => <ProductCard key={product.id} product={product} navigate={navigate} add={addToQuote} />)}</div> : <div className="empty-results"><h2>Chưa tìm thấy sản phẩm</h2><p>Hãy thử model, thương hiệu hoặc nhóm thiết bị khác.</p></div>}</div></div></section></main>
}
