import { ArrowRight, BadgeCheck, Boxes, CircleDollarSign, Headphones, Microscope, Network, ScanLine, ShieldCheck, Wrench } from 'lucide-react'
import { ProductCard } from '../components/ProductCard'
import { useStore } from '../store/StoreContext'

const categoryIcons = [Boxes, ScanLine, Microscope, Wrench, Network, ShieldCheck, CircleDollarSign, Headphones]
export function Storefront({ navigate, onQuote }: { navigate: (path: string) => void; onQuote: () => void }) {
  const { products, settings, addToQuote } = useStore(); const c = settings.content
  const categories = settings.categories.filter(item => item.visible).sort((a, b) => a.sortOrder - b.sortOrder)
  return <main>{settings.visibility.hero && <section className="hero"><div className="hero__glow" /><div className="container hero__grid"><div className="hero__copy"><span className="eyebrow">{c.heroBadge}</span><h1>{c.heroTitle}<br /><em>{c.heroHighlight}</em></h1><p>{c.heroDescription}</p><div className="hero__actions"><button className="primary-button" onClick={() => navigate('/san-pham')}>{c.heroPrimaryAction}<ArrowRight /></button><button className="secondary-button" onClick={onQuote}>{c.heroSecondaryAction}</button></div><div className="trust-row"><span><BadgeCheck />{c.trustQuality}</span><span><CircleDollarSign />{c.trustPrice}</span><span><Headphones />{c.trustSupport}</span></div></div><div className="hero__visual"><div className="orb orb--one" /><div className="orb orb--two" /><div className="tech-panel"><small>DTPT / INDUSTRIAL SYSTEMS</small><strong>{categories.length}</strong><span>NHÓM GIẢI PHÁP CỐT LÕI</span><div className="signal"><i /><i /><i /><i /><i /></div></div><div className="tech-card tech-card--a"><ScanLine /><span>Machine Vision</span></div><div className="tech-card tech-card--b"><Network /><span>Industrial IoT</span></div></div></div></section>}
  {settings.visibility.categories && <section className="section" id="linh-vuc"><div className="container"><div className="section-heading"><div><span className="eyebrow">LĨNH VỰC CUNG CẤP</span><h2>Danh mục thiết bị chuyên sâu</h2></div><p>Tập trung vào những công nghệ then chốt trong sản xuất, kiểm thử và nghiên cứu hiện đại.</p></div><div className="category-grid">{categories.map((category, index) => { const Icon = categoryIcons[index % categoryIcons.length]; return <button key={category.id} className="category-card" onClick={() => navigate(`/san-pham?category=${encodeURIComponent(category.name)}`)}><span><Icon /></span><small>{String(index + 1).padStart(2, '0')}</small><h3>{category.name}</h3><p>{category.description}</p><b>Khám phá <ArrowRight /></b></button> })}</div></div></section>}
  {settings.visibility.featuredProducts && <section className="section section--tint" id="san-pham"><div className="container"><div className="section-heading"><div><span className="eyebrow">{c.productsEyebrow}</span><h2>{c.productsTitle}</h2></div><p>{c.productsDescription}</p></div><div className="product-grid">{products.filter(product => product.featured && product.status === 'active').sort((a, b) => (a.sortOrder || 9999) - (b.sortOrder || 9999)).slice(0, 8).map(product => <ProductCard key={product.id} product={product} navigate={navigate} add={addToQuote} />)}</div><div className="center"><button className="secondary-button" onClick={() => navigate('/san-pham')}>Xem toàn bộ sản phẩm <ArrowRight /></button></div></div></section>}
  {settings.visibility.capabilities && <section className="section capability" id="nang-luc"><div className="container capability__grid"><div><span className="eyebrow">{c.whyEyebrow}</span><h2>{c.whyTitle}</h2><p>{c.whyDescription}</p></div><div className="capability__cards">{[[c.why1Title,c.why1Description],[c.why2Title,c.why2Description],[c.why3Title,c.why3Description],[c.why4Title,c.why4Description]].map(([title,description], index) => <article key={title}><b>0{index + 1}</b><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>}
  {settings.visibility.contact && <section className="contact-cta" id="lien-he"><div className="container"><span className="eyebrow">{c.contactEyebrow}</span><h2>{c.contactTitle}</h2><p>{c.contactSubtitle}</p><button className="light-button" onClick={onQuote}>Gửi yêu cầu kỹ thuật <ArrowRight /></button></div></section>}</main>
}
