import { Minus, Plus, Trash2, X } from 'lucide-react'
import { useStore } from '../store/StoreContext'

export function CartDrawer({ open, onClose, onCheckout }: { open: boolean; onClose: () => void; onCheckout: () => void }) {
  const { products, quoteItems, updateQuoteItem } = useStore()
  if (!open) return null
  return <div className={`drawer-shell ${open ? 'drawer-shell--open' : ''}`} aria-hidden={!open}><button className="drawer-backdrop" onClick={onClose} aria-label="Đóng" /><aside className="drawer"><div className="drawer__head"><div><small>DANH SÁCH</small><h2>Yêu cầu báo giá</h2></div><button className="icon-button" onClick={onClose} aria-label="Đóng danh sách báo giá"><X /></button></div><div className="drawer__body">{quoteItems.length === 0 ? <div className="empty-state"><FileIcon /><h3>Chưa có thiết bị</h3><p>Thêm sản phẩm bạn quan tâm để gửi yêu cầu kỹ thuật và nhận báo giá.</p></div> : quoteItems.map(item => { const product = products.find(value => value.id === item.productId); if (!product) return null; return <div className="quote-line" key={item.productId}><div><strong>{product.name}</strong><small>{product.brand} · {product.model}</small></div><div className="quantity"><button aria-label="Giảm số lượng" onClick={() => updateQuoteItem(item.productId, item.quantity - 1)}><Minus /></button><span>{item.quantity}</span><button aria-label="Tăng số lượng" disabled={item.quantity >= 999} onClick={() => updateQuoteItem(item.productId, item.quantity + 1)}><Plus /></button></div><button aria-label="Xóa thiết bị khỏi báo giá" className="delete-button" onClick={() => updateQuoteItem(item.productId, 0)}><Trash2 /></button></div>})}</div><div className="drawer__foot"><p>Đội ngũ DTPT Techs sẽ liên hệ để xác nhận cấu hình và yêu cầu ứng dụng.</p><button className="primary-button" onClick={onCheckout}>{quoteItems.length ? 'Gửi yêu cầu báo giá' : 'Tư vấn khi chưa chọn thiết bị'}</button></div></aside></div>
}
function FileIcon() { return <div className="empty-icon">RFQ</div> }
