import { Mail, MapPin, Phone } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { CartDrawer } from './components/CartDrawer'
import { CheckoutModal } from './components/CheckoutModal'
import { FloatingContact } from './components/FloatingContact'
import { Header } from './components/Header'
import { AdminPage } from './pages/AdminPage'
import { CatalogPage } from './pages/CatalogPage'
import { ProductDetailPage } from './pages/ProductDetailPage'
import { ArticleDetailPage } from './pages/ArticleDetailPage'
import { NewsPage } from './pages/NewsPage'
import { Storefront } from './pages/Storefront'
import { api } from './services/api'
import { useStore } from './store/StoreContext'

const SITE_URL = 'https://www.dtpt.shop'
function meta(name: string, content: string) { const key = name.startsWith('og:') ? 'property' : 'name'; const node = document.querySelector<HTMLMetaElement>(`meta[${key}="${name}"]`) ?? document.createElement('meta'); node.setAttribute(key, name); node.content = content; if (!node.parentElement) document.head.appendChild(node) }
function link(rel: string, href: string) { const node = document.querySelector<HTMLLinkElement>(`link[rel="${rel}"]`) ?? document.createElement('link'); node.rel = rel; node.href = href; if (!node.parentElement) document.head.appendChild(node) }
function structuredData(value: object) { const id = 'dtpt-structured-data'; const node = document.getElementById(id) ?? document.createElement('script'); node.id = id; node.setAttribute('type', 'application/ld+json'); node.textContent = JSON.stringify(value); if (!node.parentElement) document.head.appendChild(node) }
export function App() {
  const [route, setRoute] = useState(`${location.pathname}${location.search}`); const [search, setSearch] = useState(new URLSearchParams(location.search).get('q') || ''); const [drawer, setDrawer] = useState(false); const [modal, setModal] = useState(false); const { products, articles, settings } = useStore()
  const path = route.split('?')[0]; const params = useMemo(() => new URLSearchParams(route.split('?')[1] || ''), [route]); const product = path.startsWith('/san-pham/') ? products.find(item => item.slug === decodeURIComponent(path.slice('/san-pham/'.length))) : undefined; const article = path.startsWith('/tin-tuc/') ? articles.find(item => item.status === 'published' && item.slug === decodeURIComponent(path.slice('/tin-tuc/'.length))) : undefined
  const navigate = (next: string) => { history.pushState({}, '', next); setRoute(`${location.pathname}${location.search}`); setSearch(new URLSearchParams(location.search).get('q') || ''); scrollTo({ top: 0, behavior: 'smooth' }); setTimeout(() => { if (next.includes('#')) document.getElementById(next.split('#')[1])?.scrollIntoView({ behavior: 'smooth' }) }, 50) }
  useEffect(() => { const handler = () => setRoute(`${location.pathname}${location.search}`); addEventListener('popstate', handler); return () => removeEventListener('popstate', handler) }, [])
  useEffect(() => {
    const title = article ? (article.seoTitle || `${article.title} | ${settings.storeName}`) : product ? (product.seoTitle || `${product.name} ${product.model} | ${settings.storeName}`) : path === '/tin-tuc' ? `Tin tức công nghệ công nghiệp | ${settings.storeName}` : path === '/san-pham' ? `Thiết bị công nghiệp | ${settings.storeName}` : `${settings.storeName} | ${settings.slogan}`
    const description = article ? (article.seoDescription || article.excerpt) : product ? (product.seoDescription || product.summary) : path === '/tin-tuc' ? 'Kiến thức lựa chọn thiết bị, công nghệ mới và kinh nghiệm triển khai cho nhà máy, phòng nghiên cứu.' : settings.content.heroDescription
    const canonical = `${SITE_URL}${path === '/' ? '/' : path}`; const image = article?.coverImage || product?.images?.[0] || settings.logoWideSrc; const absoluteImage = image.startsWith('http') ? image : `${SITE_URL}${image}`
    document.title = title; meta('description', description); meta('robots', path.startsWith('/admin') ? 'noindex, nofollow' : 'index, follow, max-image-preview:large'); meta('og:title', title); meta('og:description', description); meta('og:type', article ? 'article' : product ? 'product' : 'website'); meta('og:url', canonical); meta('og:image', absoluteImage); meta('og:locale', 'vi_VN'); meta('twitter:card', 'summary_large_image'); meta('twitter:title', title); meta('twitter:description', description); meta('twitter:image', absoluteImage); link('canonical', canonical)
    structuredData(article ? { '@context': 'https://schema.org', '@type': 'Article', headline: article.title, description, image: [absoluteImage], datePublished: article.publishedAt, dateModified: article.updatedAt, author: { '@type': 'Organization', name: article.author }, publisher: { '@type': 'Organization', name: settings.storeName, logo: { '@type': 'ImageObject', url: `${SITE_URL}${settings.logoWideSrc}` } }, mainEntityOfPage: canonical } : product ? { '@context': 'https://schema.org', '@type': 'Product', name: `${product.name} ${product.model}`, description, image: product.images?.map(value => value.startsWith('http') ? value : `${SITE_URL}${value}`), brand: { '@type': 'Brand', name: product.brand }, model: product.model, sku: product.id, offers: product.price ? { '@type': 'Offer', priceCurrency: 'VND', price: product.price, availability: 'https://schema.org/PreOrder', url: canonical } : undefined } : { '@context': 'https://schema.org', '@type': 'Organization', name: settings.storeName, url: SITE_URL, logo: `${SITE_URL}${settings.logoWideSrc}`, email: settings.email, telephone: settings.phone, address: settings.address })
    api.trackPageView(route, product?.id).catch(() => undefined)
  }, [article, path, product, route, settings])
  useEffect(() => { const favicon = document.querySelector<HTMLLinkElement>('link[rel="icon"]') ?? document.createElement('link'); favicon.rel = 'icon'; favicon.href = settings.faviconSrc; favicon.removeAttribute('type'); if (!favicon.parentElement) document.head.appendChild(favicon) }, [settings.faviconSrc])
  useEffect(() => { document.documentElement.style.setProperty('--blue', settings.appearance.primaryColor); document.documentElement.style.setProperty('--cyan', settings.appearance.secondaryColor); document.documentElement.style.setProperty('--products-per-row', String(settings.appearance.productsPerRow)); document.body.dataset.cardStyle = settings.appearance.cardStyle }, [settings.appearance])
  const onSearch = (value: string) => { setSearch(value); const next = `/san-pham${value.trim() ? `?q=${encodeURIComponent(value.trim())}` : ''}`; history.replaceState({}, '', next); setRoute(next) }
  if (path.startsWith('/admin')) return <AdminPage navigate={navigate} />
  return <><Header navigate={navigate} search={search} onSearch={onSearch} onQuote={() => setDrawer(true)} />{article ? <ArticleDetailPage article={article} navigate={navigate} /> : product ? <ProductDetailPage product={product} navigate={navigate} /> : path === '/tin-tuc' ? <NewsPage navigate={navigate} /> : path === '/san-pham' ? <CatalogPage params={params} navigate={navigate} /> : <Storefront navigate={navigate} onQuote={() => setModal(true)} />}{settings.visibility.footer && <Footer navigate={navigate} />}{settings.visibility.floatingContact && <FloatingContact settings={settings} />}<CartDrawer open={drawer} onClose={() => setDrawer(false)} onCheckout={() => { setDrawer(false); setModal(true) }} /><CheckoutModal open={modal} onClose={() => setModal(false)} /></>
}
function Footer({ navigate }: { navigate: (path: string) => void }) { const { settings } = useStore(); return <footer className="footer"><div className="container footer__grid"><div><img className={`footer-logo footer-logo--${settings.logoStyle}`} src={settings.logoStyle === 'round' ? settings.logoRoundSrc : settings.logoWideSrc} alt={settings.storeName} /><p>{settings.content.footerDescription}</p></div><div><h3>Khám phá</h3><button onClick={() => navigate('/san-pham')}>Danh mục sản phẩm</button><button onClick={() => navigate('/tin-tuc')}>Tin tức & chuyên môn</button><button onClick={() => navigate('/#linh-vuc')}>Lĩnh vực cung cấp</button><button onClick={() => navigate('/#nang-luc')}>Năng lực DTPT Techs</button></div><div><h3>Liên hệ</h3><a href={`tel:${settings.phone.replace(/\s/g, '')}`}><Phone />{settings.phone}</a><a href={`mailto:${settings.email}`}><Mail />{settings.email}</a><span><MapPin />{settings.address}</span></div></div><div className="container footer__bottom"><span>© 2026 DTPT Techs. All rights reserved.</span><span>{settings.slogan}</span></div></footer> }
