import { Eye, EyeOff, Package, Pencil, Plus, Save, Search, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useStore } from '../../store/StoreContext'
import type { IndustrialCategory, Product } from '../../types'
import { Field } from './AdminField'
import { lines } from './adminUtils'

const slugify = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const emptyProduct = (category?: IndustrialCategory): Product => ({ id: `PRD-${Date.now()}`, slug: '', name: '', model: '', brand: '', origin: 'Trung Quốc', category: category?.name || '', subcategory: category?.subcategories[0] || '', priceMode: 'fixed', leadTime: 'Khoảng 2–4 tuần, xác nhận theo đơn hàng', warranty: '12 tháng', status: 'draft', featured: false, accent: '#086ad8', summary: '', highlights: [], applications: [], specifications: [], images: [], tags: [] })

export function ProductsPanel() {
  const { products, settings, saveProduct, deleteProduct } = useStore(); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Product | null>(null); const [busy, setBusy] = useState(false)
  const visible = useMemo(() => products.filter(product => `${product.name} ${product.model} ${product.brand} ${product.category} ${(product.tags || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (a.sortOrder || 9999) - (b.sortOrder || 9999)), [products, query])
  const remove = async (product: Product) => { if (!confirm(`Xóa vĩnh viễn “${product.name}”?`)) return; setBusy(true); try { await deleteProduct(product.id) } finally { setBusy(false) } }
  return <><div className="admin-toolbar"><label className="admin-search"><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Tìm tên, model, thương hiệu, tag..." /></label><span>{visible.length}/{products.length} sản phẩm</span><button className="primary-button" onClick={() => setEditing(emptyProduct(settings.categories.find(item => item.visible)))}><Plus />Thêm sản phẩm</button></div><div className="product-admin-list">{visible.map(product => <article key={product.id}><div className="product-admin-thumb">{product.images?.[0] ? <img src={product.images[0]} alt="" /> : <Package />}</div><div><strong>{product.name}</strong><span>{product.brand} · {product.model}</span><small>{product.category} / {product.subcategory}</small>{Boolean(product.tags?.length) && <div className="tag-row">{product.tags?.slice(0, 4).map(tag => <i key={tag}>{tag}</i>)}</div>}</div><div className="product-admin-price"><b>{product.price ? `${product.price.toLocaleString('vi-VN')} ₫` : 'Liên hệ'}</b><span className={`status-pill ${product.status === 'draft' ? 'status-pill--draft' : ''}`}>{product.status === 'active' ? 'Đang hiển thị' : 'Đang ẩn'}</span></div><div className="admin-row-actions"><button title="Sửa" onClick={() => setEditing(product)}><Pencil /></button><button title={product.status === 'active' ? 'Ẩn sản phẩm' : 'Hiện sản phẩm'} onClick={() => saveProduct({ ...product, status: product.status === 'active' ? 'draft' : 'active' })}>{product.status === 'active' ? <EyeOff /> : <Eye />}</button><button className="danger" title="Xóa" disabled={busy} onClick={() => remove(product)}><Trash2 /></button></div></article>)}</div>{editing && <ProductEditor product={editing} categories={settings.categories} isNew={!products.some(item => item.id === editing.id)} onClose={() => setEditing(null)} onSave={async product => { if (products.some(item => item.id !== editing.id && item.slug === product.slug)) return alert('Slug URL đã được dùng bởi sản phẩm khác.'); setBusy(true); try { await saveProduct(product); setEditing(null) } finally { setBusy(false) } }} busy={busy} />}</>
}

function ProductEditor({ product, categories, isNew, onClose, onSave, busy }: { product: Product; categories: IndustrialCategory[]; isNew: boolean; onClose: () => void; onSave: (product: Product) => Promise<void>; busy: boolean }) {
  const [form, setForm] = useState(product); const [message, setMessage] = useState(''); const currentCategory = categories.find(item => item.name === form.category)
  const set = <K extends keyof Product>(key: K, value: Product[K]) => setForm(current => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.id.trim() || !form.name.trim() || !form.model.trim() || !form.category) return setMessage('ID, tên, model và ngành hàng là bắt buộc.'); const slug = form.slug.trim() || slugify(`${form.name}-${form.model}`); void onSave({ ...form, id: form.id.trim(), slug, name: form.name.trim(), model: form.model.trim() }) }
  return <div className="admin-editor-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><form className="admin-editor" onSubmit={submit}><div className="admin-editor__head"><div><span className="eyebrow">PRODUCT EDITOR</span><h2>{product.name || 'Thêm sản phẩm mới'}</h2></div><button type="button" onClick={onClose} aria-label="Đóng"><X /></button></div><div className="admin-editor__body">
    <Field label="Tên sản phẩm" wide><input value={form.name} onChange={event => set('name', event.target.value)} required /></Field><Field label="ID"><input value={form.id} onChange={event => set('id', event.target.value)} disabled={!isNew} required /></Field><Field label="Slug URL"><input value={form.slug} onChange={event => set('slug', slugify(event.target.value))} placeholder="Tự tạo khi để trống" /></Field><Field label="Model"><input value={form.model} onChange={event => set('model', event.target.value)} required /></Field><Field label="Thương hiệu"><input value={form.brand} onChange={event => set('brand', event.target.value)} /></Field><Field label="Xuất xứ"><input value={form.origin} onChange={event => set('origin', event.target.value)} /></Field>
    <Field label="Ngành hàng"><select value={form.category} onChange={event => { const next = categories.find(item => item.name === event.target.value); setForm(value => ({ ...value, category: event.target.value, subcategory: next?.subcategories[0] || '' })) }}>{categories.map(item => <option key={item.id}>{item.name}</option>)}</select></Field><Field label="Phân nhóm"><input list="subcategories" value={form.subcategory} onChange={event => set('subcategory', event.target.value)} /><datalist id="subcategories">{currentCategory?.subcategories.map(item => <option key={item} value={item} />)}</datalist></Field>
    <Field label="Giá bán (VNĐ)"><input type="number" min="0" value={form.price ?? ''} onChange={event => set('price', event.target.value ? Number(event.target.value) : undefined)} /></Field><Field label="Kiểu giá"><select value={form.priceMode} onChange={event => set('priceMode', event.target.value as Product['priceMode'])}><option value="fixed">Giá cố định</option><option value="from">Giá từ</option><option value="range">Khoảng giá</option><option value="contact">Liên hệ</option></select></Field><Field label="Giá tối đa"><input type="number" min="0" value={form.priceMax ?? ''} onChange={event => set('priceMax', event.target.value ? Number(event.target.value) : undefined)} /></Field><Field label="Thứ tự"><input type="number" min="0" value={form.sortOrder ?? ''} onChange={event => set('sortOrder', event.target.value ? Number(event.target.value) : undefined)} /></Field>
    <Field label="Trạng thái"><select value={form.status} onChange={event => set('status', event.target.value as Product['status'])}><option value="active">Hiển thị</option><option value="draft">Ẩn / bản nháp</option></select></Field><Field label="Nhãn nổi bật"><input value={form.badge || ''} onChange={event => set('badge', event.target.value)} placeholder="Ví dụ: Bán chạy" /></Field><Field label="Màu nhấn"><input type="color" value={form.accent || '#086ad8'} onChange={event => set('accent', event.target.value)} /></Field><label className="admin-check"><input type="checkbox" checked={Boolean(form.featured)} onChange={event => set('featured', event.target.checked)} />Hiển thị ở nhóm sản phẩm nổi bật</label>
    <Field label="Mô tả ngắn" wide><textarea rows={3} value={form.summary} onChange={event => set('summary', event.target.value)} /></Field><Field label="Tag (phân cách bằng dấu phẩy)" wide><input value={(form.tags || []).join(', ')} onChange={event => set('tags', event.target.value.split(',').map(item => item.trim()).filter(Boolean))} placeholder="ADAM, Modbus, Remote I/O" /></Field><Field label="Điểm nổi bật (mỗi dòng một ý)" wide><textarea rows={4} value={form.highlights.join('\n')} onChange={event => set('highlights', lines(event.target.value))} /></Field><Field label="Ứng dụng (mỗi dòng một ý)" wide><textarea rows={4} value={form.applications.join('\n')} onChange={event => set('applications', lines(event.target.value))} /></Field>
    <Field label="Thông số (mỗi dòng: Tên: Giá trị)" wide><textarea rows={5} value={form.specifications.map(item => `${item.label}: ${item.value}`).join('\n')} onChange={event => set('specifications', lines(event.target.value).map(item => { const index = item.indexOf(':'); return { label: index > -1 ? item.slice(0, index).trim() : item, value: index > -1 ? item.slice(index + 1).trim() : '' } }))} /></Field><Field label="Ảnh sản phẩm (mỗi dòng một URL)" wide><textarea rows={4} value={(form.images || []).join('\n')} onChange={event => set('images', lines(event.target.value))} /></Field>
    <Field label="Thời gian cung cấp"><input value={form.leadTime} onChange={event => set('leadTime', event.target.value)} /></Field><Field label="Bảo hành"><input value={form.warranty} onChange={event => set('warranty', event.target.value)} /></Field><Field label="Trang hãng"><input type="url" value={form.manufacturerUrl || ''} onChange={event => set('manufacturerUrl', event.target.value)} /></Field><Field label="Datasheet"><input type="url" value={form.datasheetUrl || ''} onChange={event => set('datasheetUrl', event.target.value)} /></Field><Field label="SEO title"><input value={form.seoTitle || ''} onChange={event => set('seoTitle', event.target.value)} /></Field><Field label="SEO description"><textarea rows={2} value={form.seoDescription || ''} onChange={event => set('seoDescription', event.target.value)} /></Field>
  </div>{message && <p className="form-error editor-error">{message}</p>}<div className="admin-editor__footer"><button type="button" className="secondary-button" onClick={onClose}>Hủy</button><button className="primary-button" disabled={busy}><Save />{busy ? 'Đang lưu...' : 'Lưu sản phẩm'}</button></div></form></div>
}
