import { Plus, Save, Settings, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useStore } from '../../store/StoreContext'
import type { IndustrialCategory, SiteContent, StoreSettings } from '../../types'
import { Field } from './AdminField'
import { lines } from './adminUtils'

export function CategoriesPanel() {
  const { settings, products, updateSettings, saveProduct } = useStore(); const [items, setItems] = useState(settings.categories); const [busy, setBusy] = useState(false)
  const change = (id: string, patch: Partial<IndustrialCategory>) => setItems(value => value.map(item => item.id === id ? { ...item, ...patch } : item))
  const add = () => setItems(value => [...value, { id: `category-${Date.now()}`, name: 'Ngành hàng mới', shortName: 'New category', description: '', subcategories: [], visible: false, sortOrder: value.length + 1 }])
  const remove = (item: IndustrialCategory) => { const count = products.filter(product => product.category === item.name).length; if (count) return alert(`Không thể xóa: đang có ${count} sản phẩm thuộc ngành hàng này.`); if (confirm(`Xóa ngành hàng “${item.name}”?`)) setItems(value => value.filter(category => category.id !== item.id)) }
  const save = async () => { setBusy(true); try { for (const old of settings.categories) { const next = items.find(item => item.id === old.id); if (next && next.name !== old.name) for (const product of products.filter(item => item.category === old.name)) await saveProduct({ ...product, category: next.name }) } await updateSettings({ ...settings, categories: items }); alert('Đã lưu ngành hàng và đồng bộ sản phẩm.') } finally { setBusy(false) } }
  return <div className="admin-panel"><div className="admin-toolbar"><p>Ẩn ngành hàng không xóa sản phẩm. Khi đổi tên, hệ thống tự đồng bộ các sản phẩm liên quan.</p><button className="secondary-button" onClick={add}><Plus />Thêm ngành hàng</button><button className="primary-button" onClick={save} disabled={busy}><Save />Lưu thay đổi</button></div><div className="category-admin-list">{[...items].sort((a, b) => a.sortOrder - b.sortOrder).map(item => <article key={item.id}><div className="category-admin-head"><label className="switch"><input type="checkbox" checked={item.visible} onChange={event => change(item.id, { visible: event.target.checked })} /><span />{item.visible ? 'Đang hiển thị' : 'Đang ẩn'}</label><label>Thứ tự<input type="number" min="1" value={item.sortOrder} onChange={event => change(item.id, { sortOrder: Number(event.target.value) })} /></label><button className="danger" onClick={() => remove(item)}><Trash2 /></button></div><div className="category-admin-fields"><Field label="Tên ngành hàng"><input value={item.name} onChange={event => change(item.id, { name: event.target.value })} /></Field><Field label="Tên ngắn / tiếng Anh"><input value={item.shortName} onChange={event => change(item.id, { shortName: event.target.value })} /></Field><Field label="Mô tả" wide><textarea rows={2} value={item.description} onChange={event => change(item.id, { description: event.target.value })} /></Field><Field label="Phân nhóm (mỗi dòng một mục)" wide><textarea rows={3} value={item.subcategories.join('\n')} onChange={event => change(item.id, { subcategories: lines(event.target.value) })} /></Field></div></article>)}</div></div>
}

export function BrandingPanel() {
  const { settings, updateSettings } = useStore(); const [form, setForm] = useState(settings); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await updateSettings(form); alert('Đã cập nhật thương hiệu và thông tin liên hệ.') } finally { setBusy(false) } }
  return <form className="admin-form-card" onSubmit={submit}><section className="admin-form-section"><h2>Nhận diện thương hiệu</h2><p>Logo có thể là đường dẫn trong thư mục public hoặc URL HTTPS.</p><div className="admin-form-grid"><Field label="Tên thương hiệu"><input value={form.storeName} onChange={event => setForm({ ...form, storeName: event.target.value })} /></Field><Field label="Slogan"><input value={form.slogan} onChange={event => setForm({ ...form, slogan: event.target.value })} /></Field><Field label="Logo ngang"><input value={form.logoWideSrc} onChange={event => setForm({ ...form, logoWideSrc: event.target.value })} /></Field><Field label="Logo tròn"><input value={form.logoRoundSrc} onChange={event => setForm({ ...form, logoRoundSrc: event.target.value })} /></Field><Field label="Kiểu logo mặc định"><select value={form.logoStyle} onChange={event => setForm({ ...form, logoStyle: event.target.value as StoreSettings['logoStyle'] })}><option value="wide">Logo ngang</option><option value="round">Logo tròn</option></select></Field><div className="logo-preview"><img src={form.logoStyle === 'wide' ? form.logoWideSrc : form.logoRoundSrc} alt="Xem trước logo" /></div></div></section><section className="admin-form-section"><h2>Thông tin liên hệ</h2><div className="admin-form-grid"><Field label="Điện thoại"><input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></Field><Field label="Email"><input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></Field><Field label="Facebook"><input value={form.facebook} onChange={event => setForm({ ...form, facebook: event.target.value })} /></Field><Field label="Địa chỉ" wide><textarea rows={3} value={form.address} onChange={event => setForm({ ...form, address: event.target.value })} /></Field></div></section><button className="primary-button" disabled={busy}><Save />Lưu thông tin</button></form>
}

const groups: Array<{ title: string; description: string; fields: Array<[keyof SiteContent, string, 'input' | 'textarea']> }> = [
  { title: 'Thanh thông báo & menu', description: 'Nội dung ở phần đầu website.', fields: [['announcementPrimary', 'Thông báo chính', 'input'], ['announcementSecondary', 'Thông báo phụ', 'input'], ['navProducts', 'Menu sản phẩm', 'input'], ['navSolutions', 'Menu lĩnh vực', 'input'], ['navWhy', 'Menu giới thiệu', 'input'], ['navContact', 'Menu liên hệ', 'input']] },
  { title: 'Hero trang chủ', description: 'Thông điệp quan trọng nhất trên trang chủ.', fields: [['heroBadge', 'Dòng nhãn', 'input'], ['heroTitle', 'Tiêu đề chính', 'input'], ['heroHighlight', 'Dòng nhấn mạnh', 'input'], ['heroDescription', 'Mô tả', 'textarea'], ['heroPrimaryAction', 'Nút chính', 'input'], ['heroSecondaryAction', 'Nút phụ', 'input'], ['trustQuality', 'Cam kết 1', 'input'], ['trustPrice', 'Cam kết 2', 'input'], ['trustSupport', 'Cam kết 3', 'input']] },
  { title: 'Sản phẩm nổi bật', description: 'Tiêu đề của khối sản phẩm trang chủ.', fields: [['productsEyebrow', 'Dòng nhãn', 'input'], ['productsTitle', 'Tiêu đề', 'input'], ['productsDescription', 'Mô tả', 'textarea']] },
  { title: 'Năng lực DTPT Techs', description: 'Giới thiệu giá trị và năng lực doanh nghiệp.', fields: [['whyEyebrow', 'Dòng nhãn', 'input'], ['whyTitle', 'Tiêu đề', 'input'], ['whyDescription', 'Mô tả', 'textarea'], ['why1Title', 'Năng lực 1', 'input'], ['why1Description', 'Mô tả 1', 'textarea'], ['why2Title', 'Năng lực 2', 'input'], ['why2Description', 'Mô tả 2', 'textarea'], ['why3Title', 'Năng lực 3', 'input'], ['why3Description', 'Mô tả 3', 'textarea'], ['why4Title', 'Năng lực 4', 'input'], ['why4Description', 'Mô tả 4', 'textarea']] },
  { title: 'Liên hệ & chân trang', description: 'Lời kêu gọi liên hệ và mô tả cuối trang.', fields: [['contactEyebrow', 'Dòng nhãn liên hệ', 'input'], ['contactTitle', 'Tiêu đề liên hệ', 'input'], ['contactSubtitle', 'Mô tả liên hệ', 'textarea'], ['footerDescription', 'Mô tả chân trang', 'textarea']] },
]
export function ContentPanel() {
  const { settings, updateSettings } = useStore(); const [content, setContent] = useState(settings.content); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await updateSettings({ ...settings, content }); alert('Đã cập nhật nội dung website.') } finally { setBusy(false) } }
  return <form className="admin-content-form" onSubmit={submit}>{groups.map(group => <section className="admin-form-section" key={group.title}><h2>{group.title}</h2><p>{group.description}</p><div className="admin-form-grid">{group.fields.map(([key, label, type]) => <Field key={key} label={label} wide={type === 'textarea'}>{type === 'textarea' ? <textarea rows={3} value={content[key]} onChange={event => setContent(value => ({ ...value, [key]: event.target.value }))} /> : <input value={content[key]} onChange={event => setContent(value => ({ ...value, [key]: event.target.value }))} />}</Field>)}</div></section>)}<div className="sticky-save"><button className="primary-button" disabled={busy}><Save />Lưu toàn bộ nội dung</button></div></form>
}

export function DisplayPanel() {
  const { settings, updateSettings } = useStore(); const [form, setForm] = useState(settings); const [busy, setBusy] = useState(false)
  const labels: Array<[keyof StoreSettings['visibility'], string, string]> = [['announcement', 'Thanh thông báo', 'Dòng thông tin trên cùng'], ['hero', 'Hero trang chủ', 'Tiêu đề và thông điệp chính'], ['categories', 'Khối ngành hàng', 'Danh sách lĩnh vực trên trang chủ'], ['featuredProducts', 'Sản phẩm nổi bật', 'Các sản phẩm đã đánh dấu nổi bật'], ['capabilities', 'Khối năng lực', 'Giới thiệu thế mạnh DTPT Techs'], ['contact', 'Kêu gọi liên hệ', 'Khối liên hệ cuối trang chủ'], ['footer', 'Chân trang', 'Thông tin liên hệ và liên kết cuối trang'], ['floatingContact', 'Nút liên hệ nổi', 'Nút gọi điện và email bên phải'], ['search', 'Ô tìm kiếm', 'Tìm kiếm ở thanh menu']]
  const save = async () => { setBusy(true); try { await updateSettings(form); alert('Đã áp dụng cấu hình giao diện.') } finally { setBusy(false) } }
  return <div className="admin-display"><section className="admin-form-section"><h2>Màu sắc & thẻ sản phẩm</h2><div className="admin-form-grid"><Field label="Màu thương hiệu"><div className="color-input"><input type="color" value={form.appearance.primaryColor} onChange={event => setForm(value => ({ ...value, appearance: { ...value.appearance, primaryColor: event.target.value } }))} /><input value={form.appearance.primaryColor} onChange={event => setForm(value => ({ ...value, appearance: { ...value.appearance, primaryColor: event.target.value } }))} /></div></Field><Field label="Màu nhấn"><div className="color-input"><input type="color" value={form.appearance.secondaryColor} onChange={event => setForm(value => ({ ...value, appearance: { ...value.appearance, secondaryColor: event.target.value } }))} /><input value={form.appearance.secondaryColor} onChange={event => setForm(value => ({ ...value, appearance: { ...value.appearance, secondaryColor: event.target.value } }))} /></div></Field><Field label="Số sản phẩm mỗi hàng"><select value={form.appearance.productsPerRow} onChange={event => setForm(value => ({ ...value, appearance: { ...value.appearance, productsPerRow: Number(event.target.value) as 3 | 4 } }))}><option value={4}>4 sản phẩm</option><option value={3}>3 sản phẩm</option></select></Field><Field label="Kiểu thẻ sản phẩm"><select value={form.appearance.cardStyle} onChange={event => setForm(value => ({ ...value, appearance: { ...value.appearance, cardStyle: event.target.value as 'comfortable' | 'compact' } }))}><option value="comfortable">Đầy đủ</option><option value="compact">Gọn</option></select></Field></div></section><section className="admin-form-section"><h2>Ẩn / hiện từng khu vực</h2><p>Thay đổi chỉ ảnh hưởng cách trình bày, không xóa nội dung hoặc dữ liệu.</p><div className="visibility-grid">{labels.map(([key, label, description]) => <label key={key} className="visibility-card"><div><strong>{label}</strong><span>{description}</span></div><span className="switch"><input type="checkbox" checked={form.visibility[key]} onChange={event => setForm(value => ({ ...value, visibility: { ...value.visibility, [key]: event.target.checked } }))} /><i /></span></label>)}</div></section><button className="primary-button" onClick={save} disabled={busy}><Settings />Áp dụng giao diện</button></div>
}
